import { useEffect, useMemo, useRef, useState } from 'react'
import { Expand, Focus, Minus, Plus, RotateCcw } from 'lucide-react'
import type { Entity, EntityType, Relationship } from '../../types'

const colors: Record<EntityType, string> = { PERSON: '#51d6ff', ORGANIZATION: '#a78bfa', LOCATION: '#f5b942', PHONE: '#66d99a', VEHICLE: '#fb8b6b', ACCOUNT: '#5de0c8', TRANSACTION: '#f3c56b', EVENT: '#8592a5' }
const short = (label: string) => label.length > 16 ? `${label.slice(0, 15)}…` : label
type Position = { x: number; y: number }

export function NetworkGraph({ nodes, relationships, selectedId, onSelect, compact = false }: { nodes: Entity[]; relationships: Relationship[]; selectedId?: string; onSelect: (entity: Entity) => void; compact?: boolean }) {
  const [zoom, setZoom] = useState(1); const [positions, setPositions] = useState<Record<string, Position>>({}); const [dragging, setDragging] = useState<string | null>(null); const svg = useRef<SVGSVGElement>(null)
  const displayed = useMemo(() => nodes.slice(0, compact ? 18 : 38), [nodes, compact]); const visibleIds = new Set(displayed.map(item => item.id)); const visibleLinks = relationships.filter(item => visibleIds.has(item.source) && visibleIds.has(item.target)).slice(0, compact ? 28 : 70)
  useEffect(() => { const initial: Record<string, Position> = {}; displayed.forEach((node, index) => { if (node.id === 'person-001') { initial[node.id] = { x: 50, y: 48 }; return }; const ring = index < 12 ? 25 : 39; const angle = (index / displayed.length) * Math.PI * 2 - Math.PI / 2; initial[node.id] = { x: 50 + Math.cos(angle) * ring, y: 48 + Math.sin(angle) * ring * .72 } }); setPositions(initial) }, [displayed])
  const selectedLinks = selectedId ? visibleLinks.filter(item => item.source === selectedId || item.target === selectedId) : []
  const move = (event: React.PointerEvent<SVGSVGElement>) => { if (!dragging || !svg.current) return; const bounds = svg.current.getBoundingClientRect(); const x = Math.min(94, Math.max(6, ((event.clientX - bounds.left) / bounds.width) * 100)); const y = Math.min(91, Math.max(8, ((event.clientY - bounds.top) / bounds.height) * 100)); setPositions(prev => ({ ...prev, [dragging]: { x, y } })) }
  const reset = () => { setZoom(1); setPositions({}) }
  return <section className={`network-graph ${compact ? 'graph-compact' : ''}`}><div className="graph-canvas"><svg ref={svg} viewBox="0 0 100 100" preserveAspectRatio="none" onPointerMove={move} onPointerUp={() => setDragging(null)} onPointerLeave={() => setDragging(null)}>{[...Array(10)].map((_, i) => <line key={`v-${i}`} x1={i * 10} y1="0" x2={i * 10} y2="100" className="graph-grid" />)}{[...Array(10)].map((_, i) => <line key={`h-${i}`} x1="0" y1={i * 10} x2="100" y2={i * 10} className="graph-grid" />)}<g transform={`translate(50 50) scale(${zoom}) translate(-50 -50)`}>{visibleLinks.map(link => { const from = positions[link.source], to = positions[link.target]; if (!from || !to) return null; const active = selectedLinks.some(item => item.id === link.id); const dimmed = !!selectedId && !active; return <line key={link.id} x1={from.x} y1={from.y} x2={to.x} y2={to.y} className={`graph-edge ${active ? 'edge-active' : ''} ${dimmed ? 'edge-dimmed' : ''}`} /> })}{displayed.map(node => { const position = positions[node.id]; if (!position) return null; const active = node.id === selectedId; const connected = selectedLinks.some(link => link.source === node.id || link.target === node.id); const dimmed = !!selectedId && !active && !connected; const shape = node.type === 'ORGANIZATION' ? <rect x={position.x - 2.2} y={position.y - 2.2} width="4.4" height="4.4" rx=".8" /> : node.type === 'LOCATION' ? <path d={`M${position.x},${position.y - 2.8}c-1.8,0-3.2,1.3-3.2,3.1 0,2.4 3.2,4.8 3.2,4.8s3.2-2.4 3.2-4.8c0-1.8-1.4-3.1-3.2-3.1z`} /> : <circle cx={position.x} cy={position.y} r={node.type === 'PERSON' ? 2.45 : 1.9} />; return <g className={`graph-node node-${node.type.toLowerCase()} ${active ? 'node-active' : ''} ${dimmed ? 'node-dimmed' : ''}`} key={node.id} onClick={() => onSelect(node)} onPointerDown={event => { event.stopPropagation(); setDragging(node.id); (event.target as Element).setPointerCapture?.(event.pointerId) }} role="button" tabIndex={0} onKeyDown={event => { if (event.key === 'Enter') onSelect(node) }} aria-label={`Select ${node.label}`}><g fill={colors[node.type]}>{shape}</g><text x={position.x} y={position.y + 4.4}>{short(node.label)}</text></g> })}</g></svg></div><div className="graph-toolbar"><button onClick={() => setZoom(value => Math.min(1.7, value + .15))} aria-label="Zoom in"><Plus size={16} /></button><button onClick={() => setZoom(value => Math.max(.65, value - .15))} aria-label="Zoom out"><Minus size={16} /></button><button onClick={() => setZoom(1)} aria-label="Fit graph"><Focus size={16} /></button><button onClick={reset} aria-label="Reset graph"><RotateCcw size={16} /></button><button onClick={() => document.documentElement.requestFullscreen?.()} aria-label="Fullscreen"><Expand size={16} /></button></div></section>
}

export const graphColor = colors
